#!/bin/bash

# Kodi Tizen TPK Packaging Script
# This script creates a Tizen Package (TPK) file for Kodi

set -e

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

# Default values
BUILD_DIR="${BUILD_DIR:-$PROJECT_ROOT/build}"
PACKAGE_DIR="${PACKAGE_DIR:-$BUILD_DIR/package}"
OUTPUT_DIR="${OUTPUT_DIR:-$BUILD_DIR}"
APP_VERSION="${APP_VERSION:-21.0.0}"
PACKAGE_NAME="org.xbmc.kodi"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Logging functions
log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if required tools are available
check_requirements() {
    log_info "Checking requirements..."
    
    if [ -z "$TIZEN_SDK" ]; then
        log_error "TIZEN_SDK environment variable not set"
        log_error "Please set TIZEN_SDK to your Tizen Studio installation path"
        exit 1
    fi
    
    if [ ! -d "$TIZEN_SDK" ]; then
        log_error "TIZEN_SDK directory not found: $TIZEN_SDK"
        exit 1
    fi
    
    # Check for tizen CLI tool
    TIZEN_CLI="$TIZEN_SDK/tools/ide/bin/tizen"
    if [ ! -f "$TIZEN_CLI" ]; then
        log_error "Tizen CLI tool not found at: $TIZEN_CLI"
        exit 1
    fi
    
    log_info "Requirements check passed"
}

# Create package directory structure
create_package_structure() {
    log_info "Creating package directory structure..."
    
    # Clean and create package directory
    rm -rf "$PACKAGE_DIR"
    mkdir -p "$PACKAGE_DIR"
    
    # Create standard Tizen app directories
    mkdir -p "$PACKAGE_DIR/bin"
    mkdir -p "$PACKAGE_DIR/lib"
    mkdir -p "$PACKAGE_DIR/res"
    mkdir -p "$PACKAGE_DIR/shared"
    mkdir -p "$PACKAGE_DIR/shared/res"
    
    log_info "Package structure created at: $PACKAGE_DIR"
}

# Copy Kodi binary
copy_binary() {
    log_info "Copying Kodi binary..."
    
    local KODI_BIN="$BUILD_DIR/kodi.bin"
    if [ ! -f "$KODI_BIN" ]; then
        log_error "Kodi binary not found at: $KODI_BIN"
        log_error "Please build Kodi first"
        exit 1
    fi
    
    cp "$KODI_BIN" "$PACKAGE_DIR/bin/kodi-tizen"
    chmod +x "$PACKAGE_DIR/bin/kodi-tizen"
    
    log_info "Binary copied successfully"
}

# Copy shared libraries
copy_libraries() {
    log_info "Copying shared libraries..."
    
    # Copy Kodi's built libraries
    if [ -d "$BUILD_DIR/lib" ]; then
        find "$BUILD_DIR/lib" -name "*.so*" -exec cp -P {} "$PACKAGE_DIR/lib/" \;
    fi
    
    # Copy dependency libraries (if they exist in depends)
    local DEPENDS_LIB="$PROJECT_ROOT/tools/depends/target"
    if [ -d "$DEPENDS_LIB" ]; then
        find "$DEPENDS_LIB" -name "*.so*" -type f -exec cp -P {} "$PACKAGE_DIR/lib/" \; 2>/dev/null || true
    fi
    
    # Remove symbolic links and keep only actual library files
    find "$PACKAGE_DIR/lib" -type l -delete
    
    log_info "Libraries copied successfully"
}

# Copy UI assets and resources
copy_resources() {
    log_info "Copying UI assets and resources..."
    
    # The build system copies all assets to the build tree
    # We should copy from there to ensure we get processed assets
    local BUILD_TREE_ASSETS="$BUILD_DIR"
    
    # Copy media files (icons, fonts, images)
    if [ -d "$BUILD_TREE_ASSETS/media" ]; then
        cp -r "$BUILD_TREE_ASSETS/media" "$PACKAGE_DIR/res/"
        log_info "  - Copied media files"
    else
        log_warn "  - Media directory not found in build tree"
    fi
    
    # Copy addons (system addons are generated by the build system)
    if [ -d "$BUILD_TREE_ASSETS/addons" ]; then
        mkdir -p "$PACKAGE_DIR/res/addons"
        cp -r "$BUILD_TREE_ASSETS/addons"/* "$PACKAGE_DIR/res/addons/"
        log_info "  - Copied addons (including skins)"
    else
        log_warn "  - Addons directory not found in build tree"
    fi
    
    # Copy system files (keymaps, settings, shaders, etc.)
    if [ -d "$BUILD_TREE_ASSETS/system" ]; then
        cp -r "$BUILD_TREE_ASSETS/system" "$PACKAGE_DIR/res/"
        log_info "  - Copied system files"
    else
        log_warn "  - System directory not found in build tree"
    fi
    
    # Copy userdata templates
    if [ -d "$BUILD_TREE_ASSETS/userdata" ]; then
        cp -r "$BUILD_TREE_ASSETS/userdata" "$PACKAGE_DIR/res/"
        log_info "  - Copied userdata templates"
    else
        log_warn "  - Userdata directory not found in build tree"
    fi
    
    # Copy sounds
    if [ -d "$BUILD_TREE_ASSETS/sounds" ]; then
        cp -r "$BUILD_TREE_ASSETS/sounds" "$PACKAGE_DIR/res/"
        log_info "  - Copied sounds"
    fi
    
    # Verify critical assets are present
    local CRITICAL_ASSETS=("media" "addons" "system")
    local MISSING_ASSETS=()
    
    for asset in "${CRITICAL_ASSETS[@]}"; do
        if [ ! -d "$PACKAGE_DIR/res/$asset" ]; then
            MISSING_ASSETS+=("$asset")
        fi
    done
    
    if [ ${#MISSING_ASSETS[@]} -gt 0 ]; then
        log_error "Critical assets missing from package: ${MISSING_ASSETS[*]}"
        log_error "Please ensure the build completed successfully"
        exit 1
    fi
    
    log_info "Resources copied successfully"
}

# Copy application icons
copy_icons() {
    log_info "Copying application icons..."
    
    local ICON_SOURCE="$SCRIPT_DIR/icons/kodi.png"
    
    if [ -f "$ICON_SOURCE" ]; then
        cp "$ICON_SOURCE" "$PACKAGE_DIR/shared/res/kodi.png"
        log_info "Icon copied from packaging directory"
    elif [ -f "$PROJECT_ROOT/media/icon256x256.png" ]; then
        cp "$PROJECT_ROOT/media/icon256x256.png" "$PACKAGE_DIR/shared/res/kodi.png"
        log_info "Icon copied from media directory"
    else
        log_warn "Application icon not found, package may not display correctly"
    fi
}

# Generate tizen-manifest.xml from template
generate_manifest() {
    log_info "Generating tizen-manifest.xml..."
    
    local MANIFEST_TEMPLATE="$SCRIPT_DIR/tizen-manifest.xml.in"
    local MANIFEST_OUTPUT="$PACKAGE_DIR/tizen-manifest.xml"
    
    if [ ! -f "$MANIFEST_TEMPLATE" ]; then
        log_error "Manifest template not found at: $MANIFEST_TEMPLATE"
        exit 1
    fi
    
    # Replace version placeholder
    sed "s/@APP_VERSION@/$APP_VERSION/g" "$MANIFEST_TEMPLATE" > "$MANIFEST_OUTPUT"
    
    log_info "Manifest generated successfully"
}

# Create author signature file
create_signature_file() {
    log_info "Creating signature file..."
    
    cat > "$PACKAGE_DIR/author-signature.xml" << 'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<Signature xmlns="http://www.w3.org/2000/09/xmldsig#" Id="AuthorSignature">
<SignedInfo>
<CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"></CanonicalizationMethod>
<SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"></SignatureMethod>
</SignedInfo>
<SignatureValue></SignatureValue>
<KeyInfo>
<X509Data>
<X509Certificate></X509Certificate>
</X509Data>
</KeyInfo>
</Signature>
EOF
    
    log_info "Signature file created"
}

# Package into TPK
create_tpk() {
    log_info "Creating TPK package..."
    
    local TPK_NAME="${PACKAGE_NAME}-${APP_VERSION}.tpk"
    local TPK_PATH="$OUTPUT_DIR/$TPK_NAME"
    
    # Remove existing TPK
    rm -f "$TPK_PATH"
    
    # Check if we should sign the package
    if [ -n "$TIZEN_SECURITY_PROFILE" ]; then
        log_info "Signing TPK with security profile: $TIZEN_SECURITY_PROFILE"
        
        # Validate certificate before packaging
        "$TIZEN_CLI" security-profiles list 2>/dev/null | grep -q "$TIZEN_SECURITY_PROFILE" || {
            log_warn "Security profile '$TIZEN_SECURITY_PROFILE' not found"
            log_warn "Creating unsigned TPK instead"
            TIZEN_SECURITY_PROFILE=""
        }
    fi
    
    if [ -n "$TIZEN_SECURITY_PROFILE" ]; then
        # Create signed TPK using tizen CLI
        cd "$PACKAGE_DIR"
        "$TIZEN_CLI" package -t tpk -s "$TIZEN_SECURITY_PROFILE" -- "$PACKAGE_DIR" || {
            log_warn "Tizen CLI packaging with signing failed, creating unsigned TPK"
            TIZEN_SECURITY_PROFILE=""
        }
        
        # Move TPK to output directory if tizen CLI succeeded
        if [ -f "$PACKAGE_DIR/$TPK_NAME" ]; then
            mv "$PACKAGE_DIR/$TPK_NAME" "$TPK_PATH"
            log_info "Signed TPK created at: $TPK_PATH"
            return 0
        fi
    fi
    
    # Fallback: create unsigned TPK as a zip file
    log_info "Creating unsigned TPK..."
    cd "$PACKAGE_DIR"
    zip -r "$TPK_PATH" . -x "*.DS_Store" -x "__MACOSX/*" >/dev/null 2>&1
    
    log_info "Unsigned TPK created at: $TPK_PATH"
    log_warn "TPK is unsigned and can only be installed in developer mode"
    log_warn "To sign the TPK, run: $SCRIPT_DIR/sign.sh $TPK_PATH"
}

# Display package information
display_info() {
    log_info "Package Information:"
    echo "  Package Name: $PACKAGE_NAME"
    echo "  Version: $APP_VERSION"
    echo "  Package Directory: $PACKAGE_DIR"
    echo "  Output Directory: $OUTPUT_DIR"
    echo ""
    
    if [ -f "$OUTPUT_DIR/${PACKAGE_NAME}-${APP_VERSION}.tpk" ]; then
        local TPK_SIZE=$(du -h "$OUTPUT_DIR/${PACKAGE_NAME}-${APP_VERSION}.tpk" | cut -f1)
        echo "  TPK Size: $TPK_SIZE"
        echo ""
        log_info "Packaging completed successfully!"
        echo ""
        echo "To install on device:"
        echo "  sdb install $OUTPUT_DIR/${PACKAGE_NAME}-${APP_VERSION}.tpk"
    fi
}

# Main execution
main() {
    log_info "Starting Kodi Tizen packaging process..."
    echo ""
    
    check_requirements
    create_package_structure
    copy_binary
    copy_libraries
    copy_resources
    copy_icons
    generate_manifest
    create_signature_file
    create_tpk
    
    echo ""
    display_info
}

# Run main function
main "$@"
